export const ADD_ING = 'ADD_ING';
export const REMOVE_ING = 'REMOVE_ING';
export const SET_INGS = 'SET_INGS';
export const FETCH_INGS_FAILED = 'FETCH_INGS_FAILED';

export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILE';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';
export const ORDER_INIT = 'ORDER_INIT';

export const FETCH_ORDERS_START = 'START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAILED= 'AUTH_FAILED';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

